version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - music_network


  db:
    image: postgres:15-alpine
    container_name: music_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - music_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  music_network:
    driver: bridge
